name: Build Test

on:
  push:
    branches:
      - master
      - 'mamoru*'
      - develop


  pull_request:
    branches:
      - master
      - 'mamoru*'
      - develop


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - uses: golangci/golangci-lint-action@v4
      if: env.GIT_DIFF
      with:
        # If you change this version, be sure to also change it in contrib/devtools/Makefile.
        version: v1.54
        args: --timeout 10m --out-${NO_FUTURE}format colored-line-number
        github-token: ${{ secrets.github_token }}
    - name: No Now Usage
      if: env.GIT_DIFF
      run: scripts/no-now-lint.sh

    - name: Build with Makefile
      run: |
        make build
