name: Unit Test

on:
  push:
    branches:
      - master
      - 'mamoru*'
      - develop

  pull_request:
    branches:
      - master
      - 'mamoru*'
      - develop

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - run: go version

    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

#    - name: Setup SSH for Private Repository Access
#      uses: webfactory/ssh-agent@v0.9.0
#      with:
#        ssh-private-key: ${{ secrets.MAMORU_ETHERMINT_SSH_PRIVATE_KEY }}

    - name: Unit Test
      run: |
        make test

        




